In [2]:
#load in the numpy library
import numpy

In [3]:
#loadtxt is a function in the numpy library
#since we don't know what it takes:
numpy.loadtxt?
#this opens a documentation window at the bottom

In [6]:
#loadtxt has one required parameter: filename
#delimeter is an optional filename, but necessary for 
numpy.loadtxt(fname="python-novice-inflammation-data\data\inflammation-01.csv", delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [7]:
#set the temperature variable
temperature = 94
print temperature

94


In [8]:
#combine with words
print "The high temperature today is: " + temperature

TypeError: cannot concatenate 'str' and 'int' objects

In [9]:
#temperature is an integer and python is highly type sensitive, so convert temp
print "The high temperature today is: " + str(temperature)

The high temperature today is: 94


In [10]:
#or just print them as sepertate items
print "The high temperature today is: ", temperature
print temperature

The high temperature today is:  94
94


In [11]:
#assign the thing loadtxt creates to the variable data
data = numpy.loadtxt(fname="python-novice-inflammation-data\data\inflammation-01.csv", delimiter=',')

In [12]:
#what is data?
print data
print type(data)
print data.shape

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]
<type 'numpy.ndarray'>
(60L, 40L)


In [13]:
#lets select data - indexing
print data[59,39]
#this is the value in the 60th row, 40th column
#python indexes from 0

0.0


In [14]:
#print an entire row
print data[0,]

[  0.   0.   1.   3.   1.   2.   4.   7.   8.   3.   3.   3.  10.   5.   7.
   4.   7.   7.  12.  18.   6.  13.  11.  11.   7.   7.   4.   6.   8.   8.
   4.   4.   5.   7.   3.   4.   2.   3.   0.   0.]


In [15]:
#index backwards
print data[5:-2]
#goes from 6th row to 2nd to last row

[[ 0.  0.  1. ...,  3.  2.  1.]
 [ 0.  0.  2. ...,  1.  1.  1.]
 [ 0.  0.  1. ...,  2.  2.  1.]
 ..., 
 [ 0.  0.  1. ...,  3.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 [ 0.  1.  1. ...,  1.  1.  1.]]


In [16]:
#subset the data
small_data = data[:3, 35:]
print small_data
#: means take everything before or after

[[ 4.  2.  3.  0.  0.]
 [ 5.  1.  1.  0.  1.]
 [ 3.  2.  2.  1.  1.]]


In [17]:
print data.min()
print data.max()
print data.std()

0.0
20.0
4.61383319712


In [18]:
patient_0 = data[0]
print patient_0.max()
print patient_0.min()
print patient_0.std()

18.0
0.0
3.8983971065


In [19]:
#axis means the dimension
#numpy convention = 0- row, 1-column, 2-depth...
print data.mean(axis=1).shape

(60L,)


In [20]:
#std is called a method because it works on the data object
print data.std(axis=1)

[ 3.89839711  4.32369923  4.7581509   4.2708313   4.05555175  4.74071461
  4.20409027  5.2179977   4.61349921  5.05958249  5.03233296  4.31972221
  4.23961968  4.42012443  4.22780972  4.48441746  4.87314067  4.69680743
  4.42464688  5.09386886  4.86049123  3.99929681  4.80045571  4.59782557
  4.74447047  4.66308642  5.03959324  4.69301342  4.80045571  5.0593972
  4.34101083  4.48079234  4.31849221  4.20230591  5.54701496  4.47765284
  4.08281459  4.98773496  4.9415964   4.63546114  4.66094143  4.53865343
  4.49555336  4.50444225  4.46514277  3.86902766  5.37348816  4.53072842
  4.15301096  4.80097646  3.81575681  4.94873721  4.67379664  4.0895446
  5.02487562  4.00749298  4.84639041  4.47660586  4.71142229  4.54312668]


In [23]:
print data.dtype #data type of the individual values
print type(data) # data type of entire array


float64
<type 'numpy.ndarray'>


In [24]:
word = "software"
print type(word) #type is a function native to python (built in function)
print word.dtype #this doesn't work because dtype is specific to numpy arrays

<type 'str'>


AttributeError: 'str' object has no attribute 'dtype'